### ISSUE TITLE
Disable candle fix if bugtorch/Thaumic Mixins present

### ISSUE THREAD

**Issue by Shahelion** [rndmorris/Salis-Arcana#33]
It seems that both of those mods also implement the same fix, but none of them auto-disable of the others are present.

**Comment by rndmorris** [comment]
It currently doesn't auto-disable, correct.

In the meantime, you can set `shardMetadataCrash` and `candleMetadataCrash` to false in `config/salisarcana/bugfixes.cfg` to false to disable them.
