### ISSUE TITLE
breaks TC4Tweaks mouse scrollwheel pagination in Thaumonomicon

### ISSUE THREAD

**Issue by fluid-decanter** [rndmorris/Salis-Arcana#39]
**Describe the bug**
Using the scrollwheel with both mods installed does the right-click behavior from Salis Arcana.

**To Reproduce**
Create a new MultiMC instance with Minecraft 1.7.10, Forge, and only the mods: Unimixins, CodeChickenCore, CodeChickenLib, BaublesExpanded, Thaumcraft, TC4Tweaks, and Salis Arcana.
Make a new world in Creative mode and spawn yourself a Thaumonomicon.
Open a multi-page entry such as Aspects of Magic.
Scroll your mousewheel downward and observe as the entry is closed instead of transitioning to the next page.

Now for a second variant of the bug.
Open a research entry, such as Ores.
Exit this entry with the Escape key, not right-click.
Now open a different entry, such as Auras and Nodes.
Scroll your mousewheel downward and observe as you are taken to the previous research entry you viewed, instead of transitioning to the next page of the current entry.

**Additional context**
Disabling Right-Click Navigation in Salis Arcana config removes the issue, so it is almost certainly a bug with that.

**Comment by Midnight145** [comment]
Sorry about that! Not sure how I missed that in my testing.

**Comment by Midnight145** [comment]
Update, this will be fixed in the next tc4tweaks update instead of here to help avoid any potential future compatibility issues

**Comment by Glease** [comment]
>  next tc4tweaks update

which is 1.5.28
